services:
  - type: web
    name: amath-sg
    runtime: node
    # closest Render region to players in Thailand
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
